services:
  dashy:
    image: lissy93/dashy:release-3.1.12
    container_name: dashy
    restart: unless-stopped
    environment:
    - TZ=America/New_York
    - UID=99
    - GID=100
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=dashy
    - NODE_ENV=production
    - DISABLE_DEV_MODE=true
    - PORT=8080
    - DIRECTORY=/app
    - IS_DOCKER=true
    - VUE_APP_DOMAIN=/
    - BASE_URL=/
    ports:
    - 4000:8080
    labels:
    - traefik.enable=true
    - traefik.docker.network=internal_net
    - traefik.http.routers.dashy.rule=Host(`dashy.${DOMAIN}`)
    - traefik.http.routers.dashy.entrypoints=web
    - traefik.http.routers.dashy.middlewares=crowdsec@file
    - traefik.http.services.dashy.loadbalancer.server.port=8080
    - kuma.dashy.type=http
    - kuma.dashy.url=http://dashy:8080
    - kuma.dashy.name=Dashy Dashboard
    - kuma.dashy.interval=60
    - kuma.dashy.keyword=Dashy
    - kuma.dashy.tags=utilities,dashboard
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/dashy-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:4000]
    volumes:
    - ${APPDATA_PATH}/dashy:/app/user-data
    - ${APPDATA_PATH}/dashy/icons:/app/user-data/item-icons
    networks:
    - internal_net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.02'
          memory: 32M
networks:
  internal_net:
    external: true
